build:
    RUSTFLAGS="-C strip=none --emit=llvm-ir -C debuginfo=2" cargo build --target=wasm32-unknown-unknown --release --features certora

wasm2wat :=  "wasm2wat"
wat2wasm := "wat2wasm"

wat: build
    {{wasm2wat}} target/wasm32-unknown-unknown/release/soroban_hello_world_contract.wasm --generate-names -o foo.wat
    {{wat2wasm}} foo.wat --debug-names -o bar.wasm
    {{wasm2wat}} bar.wasm -o soroban_hello_world_contract.wat
    rm foo.wat bar.wasm

build-llvm:
    env RUSTFLAGS="--emit=llvm-ir" cargo build --target=wasm32-unknown-unknown --release
    @echo "See target/wasm32-unknown-unknown/release/deps/soroban_hello_world_contract.ll"

clean:
    cargo clean

update:
    cargo update -p nondet
