#!/bin/bash

SBF=spl_token_2022.so
INLINE_CFG=cvt_inlining.txt
SUMMARY_CFG=cvt_summaries.txt

PROVER_ARGS="-solanaOptimisticSlicerIgnoresStackWidths true -solanaOptimisticJoin true -solanaOptimisticOverlaps true -solanaInlining $INLINE_CFG -solanaSummaries $SUMMARY_CFG -solanaEntrypoint integrity_of_process_mint_to"

certoraRun.py $SBF \
	      --prover_args "${PROVER_ARGS}" \
	      --prover_version jorge/solana-dev --server staging --debug
